play_motion:
  motions:
    o22:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [1.011, 0.2148, -1.1407, 1.0227, -1.5298, 0.5698, -1.5782]
        - time_from_start: 2
          positions: [0.939, 0.183, -1.3074, 1.0479, -1.6315, 0.5706, -1.5775]
        - time_from_start: 10
          positions: [1.4105, 0.2109, -1.1399, 0.6501, -1.5298, 0.57, -1.58]
      meta:
        name: o22
        usage: o22
        description: offer token p22  to user right side