play_motion:
  motions:
    ss31:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to p33
        - time_from_start: 3
          positions: [0.6256, 0.3918, -1.4047, 1.4211, -1.7882, 0.5703, -1.5774]
        #go to p31
        - time_from_start: 5
          positions: [0.9706, 0.3627, -1.269, 1.3155, -1.6315, 0.5706, -1.5775]
        #go to p33
        - time_from_start: 7
          positions: [0.6256, 0.3918, -1.4047, 1.4211, -1.7882, 0.5703, -1.5774]
        #come back
        - time_from_start: 10
          positions: [0.2269, 0.3316, -1.6138, 2.2556, -1.6316, 0.5703, -1.5773]
      meta:
        name: ss31
        usage: ss31
        description: suggest a subset of solution from p31

