play_motion:
  motions:
    c23:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.8865, 0.218, -1.1412, 1.0227, -1.5298, 0.5698, -1.5782]
        - time_from_start: 2
          positions: [0.8251, 0.18, -1.3074, 1.0541, -1.6315, 0.5706, -1.5775]
        - time_from_start: 5
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
      meta:
        name: c23
        usage: c23
        description: coming back a token in position c24 with intermediate point