play_motion:
  motions:
    c45:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.301, 0.3004, -1.2996, 1.4801, -1.63, 0.5701, -1.5801]
        - time_from_start: 2
          positions: [0.3294, 0.5073, -1.299, 1.5193, -1.6312, 0.5705, -1.5776]
        - time_from_start: 5
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
      meta:
        name: c45
        usage: c45
        description: coming back a token in position c45 with intermediate point