play_motion:
  motions:
    o24:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.7781, 0.2187, -1.1412, 1.0227, -1.5298, 0.5698, -1.5782]
        - time_from_start: 5
          positions: [0.7189, 0.183, -1.3074, 1.0541, -1.6314, 0.5706, -1.5775]
        - time_from_start: 10
          positions: [0.6997, 0.2705, -1.1202, 0.6501, -1.5499, 0.5702, -1.5802]
      meta:
        name: o24
        usage: o24
        description: offer token p14 to user left side