play_motion:
  motions:
    p14:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        - time_from_start: 3
          positions: [0.9346, 0.1891, -1.1414, 0.6464, -1.5298, 0.5699, -1.5782]
        - time_from_start: 5
          positions: [1.0192, 0.1005, -1.1193, 0.5701, -1.5496, 0.57, -1.5801]
      meta:
        name: p14
        usage: p14
        description: pick a token in position p14 with intermediate point