play_motion:
  motions:
    p15:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        - time_from_start: 3
          positions: [0.879, 0.18, -1.1413, 0.5973, -1.5298, 0.5699, -1.5782]
        - time_from_start: 5
          positions: [0.9676, 0.0713, -1.1193, 0.4847, -1.5498, 0.57, -1.5801]
      meta:
        name: p15
        usage: p15
        description: pick a token in position p15 with intermediate point