play_motion:
  motions:
    s14:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to p14
        - time_from_start: 3
          positions: [1.0192, 0.22, -1.1193, 0.5701, -1.5496, 0.57, -1.5801]
        #go to p13
        - time_from_start: 5
          positions: [1.0192, 0.1607, -1.1193, 0.5701, -1.5496, 0.57, -1.5801]
        #go to p12
        - time_from_start: 7
          positions: [1.0192, 0.22, -1.1193, 0.5701, -1.5496, 0.57, -1.5801]
        #come back
        - time_from_start: 10
          positions: [0.2269, 0.3316, -1.6138, 2.2556, -1.6316, 0.5703, -1.5773]
      meta:
        name: s14
        usage: s14
        description: suggest the solution for p14