play_motion:
  motions:
    c13:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [1.0791, 0.1331, -1.1193, 0.6565, -1.5498, 0.57, -1.5801]
        - time_from_start: 2
          positions: [1.0323, 0.1891, -1.1414, 0.6464, -1.5298, 0.5699, -1.5782]
        - time_from_start: 5
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
      meta:
        name: c13
        usage: c13
        description: come back from position p13 to intermediate point