play_motion:
  motions:
    c32:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.8871, 0.3781, -1.1497, 1.3456, -1.6315, 0.5706, -1.5775]
        - time_from_start: 5
          positions: [0.8808, 0.5741, -1.1959, 1.3947, -1.6315, 0.5706, -1.5775]
        - time_from_start: 10
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
      meta:
        name: c32
        usage: c32
        description: place a token in position c32 with intermediate point