play_motion:
  motions:
    c41:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.86, 0.4201, -1.2799, 1.58, -1.63, 0.57, -1.58]
        - time_from_start: 2
          positions: [0.87, 0.5943, -1.2749, 1.5802, -1.6308, 0.5703, -1.5778]
        - time_from_start: 5
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        
      meta:
        name: c41
        usage: c41
        description: coming back a token in position c41 with intermediate point