play_motion:
  motions:
    c42:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.7501, 0.5998, -1.2099, 1.6399, -1.63, 0.5699, -1.5803]
        - time_from_start: 2
          positions: [0.7796, 0.7522, -1.2092, 1.6385, -1.6313, 0.5704, -1.5777]
        - time_from_start: 5
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        
      meta:
        name: c42
        usage: c42
        description: coming back a token in position c42 with intermediate point