play_motion:
  motions:
    o11:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 5
          positions: [1.2786, 0.1091, -1.1414, 0.6463, -1.5298, 0.5698, -1.5781]
        - time_from_start: 10
          positions: [1.2786, 0.1891, -1.1414, 0.6463, -1.5298, 0.5698, -1.5781]
        - time_from_start: 15
          positions: [1.4105, 0.2109, -1.1399, 0.6501, -1.5298, 0.57, -1.58]
      meta:
        name: o11
        usage: o11
        description: offer token p11  to user right side