play_motion:
  motions:
    o12:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [1.1657, 0.1091, -1.1414, 0.6463, -1.5298, 0.5699, -1.5782]
        - time_from_start: 5
          positions: [1.1657, 0.1891, -1.1414, 0.6463, -1.5298, 0.5699, -1.5782]
        - time_from_start: 10
          positions: [1.4105, 0.2109, -1.1399, 0.6501, -1.5298, 0.57, -1.58]
      meta:
        name: o12
        usage: o12
        description: offer token in position p12 to user