play_motion:
  motions:
    o14:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.9346, 0.147, -1.1412, 0.7327, -1.55, 0.5702, -1.5802]
        - time_from_start: 5
          positions: [0.9346, 0.1891, -1.1414, 0.6464, -1.5298, 0.5699, -1.5782]
        - time_from_start: 10
          positions: [0.6997, 0.2705, -1.1202, 0.6501, -1.5499, 0.5702, -1.5802]
      meta:
        name: o14
        usage: o14
        description: offer token in position p14 to user