play_motion:
  motions:
    o15:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.879, 0.1324, -1.1163, 0.6545, -1.55, 0.5702, -1.5802]
        - time_from_start: 5
          positions: [0.879, 0.18, -1.1413, 0.5973, -1.5298, 0.5699, -1.5782]
        - time_from_start: 10
          positions: [0.6997, 0.2705, -1.1202, 0.6501, -1.5499, 0.5702, -1.5802]
      meta:
        name: o15
        usage: o15
        description: offer token in position p15 to user