play_motion:
  motions:
    o15:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.9676, 0.0713, -1.1193, 0.4847, -1.5498, 0.57, -1.5801]
        - time_from_start: 2
          positions: [0.879, 0.18, -1.1413, 0.5973, -1.5298, 0.5699, -1.5782]
        - time_from_start: 10
          positions: [0.6997, 0.2705, -1.1202, 0.6501, -1.5499, 0.5702, -1.5802]
      meta:
        name: o15
        usage: o15
        description: offer token in position p15 to user