play_motion:
  motions:
    o21:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.9902, 0.2905, -1.2072, 1.3062, -1.6315, 0.5706, -1.5775]
        - time_from_start: 5
          positions: [0.9706, 0.3627, -1.269, 1.3155, -1.6315, 0.5706, -1.5775]
        - time_from_start: 10
          positions: [1.4105, 0.2109, -1.1399, 0.6501, -1.5298, 0.57, -1.58]
      meta:
        name: o21
        usage: o21
        description: offer token in position p21 to user