play_motion:
  motions:
    o32:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.8871, 0.3781, -1.1497, 1.3456, -1.6315, 0.5706, -1.5775]
        - time_from_start: 5
          positions: [0.8808, 0.5741, -1.1959, 1.3947, -1.6315, 0.5706, -1.5775]
        - time_from_start: 10
          positions: [1.4105, 0.2109, -1.1399, 0.6501, -1.5298, 0.57, -1.58]
      meta:
        name: o32
        usage: o32
        description: offer token p32  to user right side