play_motion:
  motions:
    p23:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        - time_from_start: 3
          positions: [0.8251, 0.18, -1.3074, 1.0541, -1.6315, 0.5706, -1.5775]
        - time_from_start: 5
          positions: [0.8203, 0.1101, -1.3099, 1.05, -1.6297, 0.5302, -1.5802]
      meta:
        name: p23
        usage: p23
        description: pick a token in position p23 with intermediate point