play_motion:
  motions:
    p24:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        - time_from_start: 3
          positions: [0.7189, 0.183, -1.3074, 1.0541, -1.6314, 0.5706, -1.5775]
        - time_from_start: 5
          positions: [0.7502, 0.1102, -1.3099, 0.98, -1.6596, 0.57, -1.5802]
        - time_from_start: 6.5
          positions: [0.7781, 0.2187, -1.1412, 1.0227, -1.5298, 0.5698, -1.5782]
      meta:
        name: p24
        usage: p24
        description: pick a token in position p24 with intermediate point