play_motion:
  motions:
    p25:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        - time_from_start: 3
          positions: [0.64, 0.2, -1.2499, 1.0199, -1.6, 0.5399, -1.5499]
        - time_from_start: 5
          positions: [0.6999, 0.1201, -1.25, 0.8897, -1.5998, 0.5403, -1.5503]
        - time_from_start: 10
          positions: [0.7063, 0.1887, -1.1412, 0.9305, -1.5298, 0.5698, -1.5782]
      meta:
        name: p25
        usage: p25
        description: pick a token in position p25 with intermediate point