play_motion:
  motions:
    p33:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        - time_from_start: 5
          positions: [0.7119, 0.4834, -1.2491, 1.3931, -1.6315, 0.5706, -1.5775]
        - time_from_start: 10
          positions: [0.7396, 0.3237, -1.1922, 1.3392, -1.6315, 0.5706, -1.5775]
      meta:
        name: p33
        usage: p33
        description: pick a token in position p33 with intermediate point