play_motion:
  motions:
    s13:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to step1
        - time_from_start: 3
          positions: [1.0791, 0.225, -1.1193, 0.6565, -1.5498, 0.57, -1.5801]
        #go to step2
        - time_from_start: 5
          positions: [1.0791, 0.1631, -1.1193, 0.6565, -1.5498, 0.57, -1.5801]
        #go to step3
        - time_from_start: 7
          positions: [1.0791, 0.225, -1.1193, 0.6565, -1.5498, 0.57, -1.5801]
        #come back
        - time_from_start: 10
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
      meta:
        name: s13
        usage: s13
        description: suggest the solution for p13