play_motion:
  motions:
    s15:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to 1ststep
        - time_from_start: 3
          positions: [0.9676, 0.16, -1.1193, 0.4847, -1.5498, 0.57, -1.5801]
        #go to 2ndstep
        - time_from_start: 5
          positions: [0.9676, 0.1, -1.1193, 0.4847, -1.5498, 0.57, -1.5801]
        #go to 3rdstep
        - time_from_start: 7
          positions: [0.9676, 0.16, -1.1193, 0.4847, -1.5498, 0.57, -1.5801]
        #come back
        - time_from_start: 10
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
      meta:
        name: s15
        usage: s15
        description: suggest the solution for p15