play_motion:
  motions:
    s23:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to first step
        - time_from_start: 5
          positions: [0.8251, 0.223, -1.3074, 1.0541, -1.6315, 0.5706, -1.5775]
        #go to second step
        - time_from_start: 10
          positions: [0.8251, 0.183, -1.3074, 1.0541, -1.6315, 0.5706, -1.5775]
        #go to third step
        - time_from_start: 15
          positions: [0.8251, 0.223, -1.3074, 1.0541, -1.6315, 0.5706, -1.5775]
        #come back
        - time_from_start: 20
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
      meta:
        name: s23
        usage: s23
        description: suggest the solution for p23